# Site settings
title: How Should I Use This?
header-img: img/home-bg.png
email: rschmelter33@gmail.com
copyright_name: rschmelter
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on coding as a tool for good
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rschmelter
learn_profile: rschmelter
email_username: rschmelter33@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
